if(!requireNamespace(devtools, quietly = TRUE)) install.packages("devtools") 

install.packages('Seurat')
devtools::install_github("zijianni/scCB2")
devtools::install_github('EDePasquale/DoubletDecon')
devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')
devtools::install_github("mohuangx/SAVER")
devtools::install_github("ikwak2/DrImpute")
devtools::install_github("ChongC1990/scRMD")
devtools::install_github("Vivianstats/scImpute")
devtools::install_github("BIMSBbioinfo/netSmooth")
devtools::install_github("BMILAB/scLINE")
devtools::install_github("VCCRI/CIDR")
devtools::install_github("BMILAB/scNPF")
devtools::install_github("seasamgo/rescue")
devtools::install_github("WT215/bayNorm")
devtools::install_github("cnk113/scRecover")
devtools::install_github("cnk113/ESCAPE/scDoc")
devtools::install_github("cnk113/ESCAPE/ADImpute_v1.1")
devtools::install_github("software-github/SCRABBLE/R")
devtools::install_github("Zhangxf-ccnu/scTSSR", subdir="pkg")
devtools::install_github("ChenMengjie/VIPER")
devtools::install_github("cnk113/ESCAPE/pkg")
